config/routes.rb
Helloword::Application.routes.draw do
  root to: 'hello#world'

  get '/hello/world'=>'hello#world'
  get '/pessoas/adultos' => 'pessoas#adultos'
  get '/pessoas/criancas' => 'pessoas#criancas'
  #get '/cidades/santa_catarina' => 'cidades#santa_catarina'
  #get '/cidades/parana' => 'cidades#parana'
  resources :cidades
  resources :estados
  resources :paises
  resources :bairros
  resources :ceps

  get '/estados' => 'estados#index'
end
  

app/models/bairro.rb
class Bairro < ActiveRecord::Base
  attr_accessible :nome, :cidade_id

  belongs_to :cidade
  has_many :ceps

  validates :nome,
    presence: true,
    length: {
      maximum: 32
    }
end 

app/models/cep.rb
class Cep < ActiveRecord::Base
    attr_accessible :logradouro, :cep, :bairro_id

    belongs_to :bairro

    validates :logradouro,
      presence: true,
      length: {
        maximum: 128
      }
end

app/models/cidade.rb
class Cidade <ActiveRecord::Base
  attr_accessible :nome, :qtde_habitantes, :estado_id

  belongs_to :estado
  has_many :bairros

  validates :nome,
    presence: true,
    length: {
      maximum: 32
    }

  validates :qtde_habitantes,
    presence: true,
    numericality: {
      greater_than_or_equal_to: 0
    }

 
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  attr_accessible :nome, :sigla, :pais_id

  belongs_to :pais
  has_many :cidades

  has_many :cidades

  validates :nome,
    presence: true,
    length: {
      maximum: 32
    }

  validates :sigla,
    presence: true,
    length: {
      maximum: 2
    },
    uniqueness: true
end

app/models/pais.rb
class Pais < ActiveRecord::Base
  attr_accessible :nome

  has_many :estados

  validates :nome,
    presence: true,
    length: {
      maximum: 32
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bairros_controller.rb
class BairrosController  < ApplicationController
  include ActionView::Helpers::FormOptionsHelper

  def index
    @bairros = Bairro.all
  end

  def new
    @bairro = Bairro.new
  end

  def create
    @bairro = Bairro.new(params[:bairro])

    if @bairro.save
      flash[:success] = 'Bairro cadastrado com sucesso'
      redirect_to @bairro
    else
      render action: :new
    end
  end

  def show
    @bairro = Bairro.find(params[:id])
  end

  def edit
    @bairro = Bairro.find(params[:id])
  end

  def update
    @bairro = Bairro.find(params[:id])

    if @bairro.update_attributes(params[:bairro])
      flash[:success] = 'Bairro atualizado com sucesso'
      redirect_to @bairro
    else
      render action: :edit
    end
  end

  def destroy
    @bairro = Bairro.find(params[:id])
    @bairro.destroy

    redirect_to action: :index
  end
end

app/controllers/ceps_controller.rb
class CidadesController < ApplicationController
    include ActionView::Helpers::FormOptionsHelper
  
    def index
      @cidades = Cidade.all
    end
  
    def new
      @cidade = Cidade.new
    end
  
    def create
      @cidade = Cidade.new(params[:cidade])
  
      if @cidade.save
        flash[:success] = 'Cidade cadastrada com sucesso'
        redirect_to @cidade
      else
        render action: :new
      end
    end
  
    def show
      @cidade = Cidade.find(params[:id])
    end
  
    def edit
      @cidade = Cidade.find(params[:id])
    end
  
    def update
      @cidade = Cidade.find(params[:id])
  
      if @cidade.update_attributes(params[:cidade])
        flash[:success] = 'Cidade atualizada com sucesso'
        redirect_to @cidade
      else
        render action: :edit
      end
    end
  
    def destroy
      @cidade = Cidade.find(params[:id])
      @cidade.destroy
  
      redirect_to action: :index
    end
  
    def bairros
      cidade = Cidade.find(params[:id])
  
      bairros = [[]]
      cidade.bairros.each do |bairro|
        bairros << [ bairro.nome, bairro.id ]
      end
  
      render text: options_for_select(bairros)
    end
  end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  include ActionView::Helpers::FormOptionsHelper
  def index
      @cidades =Cidade.all 
  end

  def new
    @cidade = Cidade.new
    end

  def create
    @cidade = Cidade.new(params[:cidade])
    if @cidade.save 
      flash[:success] = 'Cidade cadastrada com sucesso'
      redirect_to @cidade  
    else
      render action: :new
    end
  end
  def edit
    @cidade = Cidade.find(params[:id])
  end
  def update
    @cidade = Cidade.find(params[:id])
    
    if @cidade.update_attributes(params[:cidade])
      flash[:success] = 'Cidade atualizada com sucesso'
      redirect_to @cidade
    else
      render action: :edit
    end
  end

  def destroy
    @cidade = Cidade.find(params[:id])
    @cidade.destroy
    redirect_to :action => :index
  end
  def show
    @cidade =Cidade.find(params[:id])
  end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  include ActionView::Helpers::FormOptionsHelper

  def index
    @estados = Estado.all
  end

  def new
    @estado = Estado.new
  end

  def create
    @estado = Estado.new(params[:estado])

    if @estado.save
      flash[:success] = 'Estado cadastrado com sucesso'
      redirect_to @estado
    else
      render action: :new
    end
  end

  def show
    @estado = Estado.find(params[:id])
  end

  def edit
    @estado = Estado.find(params[:id])
  end

  def update
    @estado = Estado.find(params[:id])

    if @estado.update_attributes(params[:estado])
      flash[:success] = 'Estado atualizado com sucesso'
      redirect_to @estado
    else
      render action: :edit
    end
  end

  def destroy
    @estado = Estado.find(params[:id])
    @estado.destroy

    redirect_to action: :index
  end

  def cidades
    estado = Estado.find(params[:id])

    cidades = [[]]
    estado.cidades.each do |cidade|
      cidades << [ cidade.nome, cidade.id ]
    end

    render text: options_for_select(cidades)
  end
end

app/controllers/hello_controller.rb

class HelloController < ApplicationController
    def world
        @alfabeto=%w{a b c d e f g h i j k l m n o p q r s t u v w x y z}
        @hash= {:chave => 'valor'}
        @pessoas= [    {:nome => 'João'}]
        @pessoas= [    {:nome => 'João'}]
    end
end

app/controllers/paises_controller.rb
class PaisesController < ApplicationController
  include ActionView::Helpers::FormOptionsHelper
  def index
      @paises = Pais.all 
  end
  def new
    @pais = Pais.new
  end

  def create
    @pais = Pais.new(params[:pais])
    if @pais.save 
      flash[:success] = 'Pais cadstrado com sucesso'
      redirect_to @pais  
    else
      render action: :new
    end
  end
  def edit
    @pais = Pais.find(params[:id])
  end
  def update
    @pais = Pais.find(params[:id])
    
    if @pais.update_attributes(params[:pais])
      flash[:success] = 'Pais atualizado com sucesso'
      redirect_to @pais
    else
      render action: :edit
    end
  end

  def destroy
    @pais = Pais.find(params[:id])
    @pais.destroy
    redirect_to :action => :index
  end
  def show
    @pais =Pais.find(params[:id])
  end
end

app/controllers/pessoas_controller.rb
class PessoasController <ApplicationController
    def adultos
        @adultos =[
            {nome: 'jose', idade: 35},
            {nome: 'gutsavb', idade: 12}
        ]
    end
    def criancas
        @criancas =[
            {nome: 'maria', idade: 9},
            {nome: 'joao', idade: 7}
        ]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bairros/_formulario.html.erb
<% if @bairro.errors.any? %>
  <div style='color:red;'>
    Não foi possível salvar o bairro por <%=
    pluralize(@cidade.errors.size, 'motivo') %>:
    <ul>
      <% @bairro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @bairro do |f| %>

  <%= f.label :nome %><br>
  <%= f.text_field :nome, maxlength: 32, required: true %><br>
  
  <%= f.submit "Submit" %>
<% end %>

app/views/bairros/_lista_de_cidades.html.erb
<table>
    <thead>
    <tr><th colspan="2">Lista Bairros</th></tr>
    </thead>

    <tr>
        <th>Nome</th>
    </tr>   
    <% bairros.each do |bairro| %>
    <tr><td><%= bairro[:nome] %></td>
    <% end %>
</table>

app/views/bairros/edit.html.erb
<h1>Editar bairro</h1>

<%= render partial: 'formulario' %>

app/views/bairros/index.html.erb
<h1>Lista de Bairros</h1>
<table>
    <thead>
        <tr>
            <th>Nome</th>
        <tr>
    <thead>
    <tbody>
        <% @bairros.each do |bairro|%>
            <tr>
                <td><%= bairro.nome%></td>
               
                <td>
                    <%= link_to({:action => :destroy, :id => bairro.id},method: :delete,
                        :confirm => "Você tem certeza?") do %>
                        <%= image_tag 'https://icons.iconarchive.com/icons/awicons/vista-artistic/16/delete-icon.png' %>
                    <% end %>
                </td>
                <td>
                    <%= link_to "Editar", edit_bairro_path(bairro.id) %>
                </td>
                <td>
                    <%= link_to "Visualizar" ,  bairro%>
                </td>
                <td>
                    <%= link_to(:action => :edit, :id => bairro.id) do %>
                    <%= image_tag 'page_edit.png' %>
                    <% end %>
                </td> 
            </tr>
        <%end%>
    </tbody>
    <%= link_to 'Nova Bairro', new_bairro_path %>
</table>

app/views/bairros/new.html.erb
<h1>Criar bairro</h1>

<%= render partial: 'formulario' %>

app/views/bairros/show.html.erb
<p><%= @bairro.nome %></p>

app/views/cep/_formulario.html.erb
<% if @cep.errors.any? %>
  <div style='color:red;'>
    Não foi possível salvar o cep por <%=
    pluralize(@cep.errors.size, 'motivo') %>:
    <ul>
      <% @cep.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @cep do |f| %>

  <%= f.label :logradouro%><br>
  <%= f.text_field :logradouro, maxlength: 32, required: true %><br>

  <%= f.label :cep, 'Qtde. habitantes' %><br>
  <%= f.text_field :cep,  maxlength: 32, required: true %><br>
   <%= f.label :bairro_id, 'Bairro' %><br>
 
    <%= f.select :estado_id, options_from_collection_for_select(Estado.all, :id, :sigla, @cidade.estado_id) %><br>
  
  <%= f.submit "Submit" %>
<% end %>

app/views/cep/_lista_de_cidades.html.erb
<table>
    <thead>
    <tr><th colspan="2">Lista Cidades</th></tr>
    </thead>

    <tr>
        <th>Nome</th>
        <th>N de Habitantes</th>
    </tr>   
    <% cidades.each do |cidade| %>
    <tr><td><%= cidade[:nome] %></td
    ><td><%= cidade[:habitantes] %> anos</td></tr>    
    <% end %>
</table>

app/views/cep/edit.html.erb
<h1>Editar cidade</h1>

<%= render partial: 'formulario' %>

app/views/cep/index.html.erb
<h1>Lista de cidades</h1>
<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Estado</th>
            <th>qtd Habitantes</th>
        <tr>
    <thead>
    <tbody>
        <% @cidades.each do |cidade|%>
            <tr>
                <td><%= cidade.nome%></td>
                <td><%= cidade.estado.nome%></td>
                <td><%= cidade.qtde_habitantes%></td>
                <td>
                    <%= link_to({:action => :destroy, :id => cidade.id},method: :delete,
                        :confirm => "Você tem certeza?") do %>
                        <%= image_tag 'https://icons.iconarchive.com/icons/awicons/vista-artistic/16/delete-icon.png' %>
                    <% end %>
                </td>
                <td>
                    <%= link_to "Editar", edit_cidade_path(cidade.id) %>
                </td>
                <td>
                    <%= link_to "Visualizar" ,  cidade%>
                </td>
                <td>
                    <%= link_to(:action => :edit, :id => cidade.id) do %>
                    <%= image_tag 'page_edit.png' %>
                    <% end %>
                </td> 
            </tr>
        <%end%>
    </tbody>
    <%= link_to 'Nova cidade', new_cidade_path %>
</table>

app/views/cep/new.html.erb
<h1>Criar cidade</h1>

<%= render partial: 'formulario' %>

app/views/cep/show.html.erb
<p><%= @cidade.nome %></p>

<p><%= @cidade.qtde_habitantes %></p>

app/views/cidades/_formulario.html.erb
<% if @cidade.errors.any? %>
  <div style='color:red;'>
    Não foi possível salvar a cidade por <%=
    pluralize(@cidade.errors.size, 'motivo') %>:
    <ul>
      <% @cidade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @cidade do |f| %>

  <%= f.label :nome %><br>
  <%= f.text_field :nome, maxlength: 32, required: true %><br>

  <%= f.label :qtde_hambiatntes, 'Qtde. habitantes' %><br>
  <%= f.text_field :qtde_habitantes,  maxlength: 32, required: true %><br>
   <%= f.label :estado_id, 'Estado' %><br>
 
    <%= f.select :estado_id, options_from_collection_for_select(Estado.all, :id, :sigla, @cidade.estado_id) %><br>
  
  <%= f.submit "Submit" %>
<% end %>

app/views/cidades/_lista_de_cidades.html.erb
<table>
    <thead>
    <tr><th colspan="2">Lista Cidades</th></tr>
    </thead>

    <tr>
        <th>Nome</th>
        <th>N de Habitantes</th>
    </tr>   
    <% cidades.each do |cidade| %>
    <tr><td><%= cidade[:nome] %></td
    ><td><%= cidade[:habitantes] %> anos</td></tr>    
    <% end %>
</table>

app/views/cidades/edit.html.erb
<h1>Editar cidade</h1>

<%= render partial: 'formulario' %>

app/views/cidades/index.html.erb
<h1>Lista de cidades</h1>
<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Estado</th>
            <th>qtd Habitantes</th>
        <tr>
    <thead>
    <tbody>
        <% @cidades.each do |cidade|%>
            <tr>
                <td><%= cidade.nome%></td>
                <td><%= cidade.estado.nome%></td>
                <td><%= cidade.qtde_habitantes%></td>
                <td>
                    <%= link_to({:action => :destroy, :id => cidade.id},method: :delete,
                        :confirm => "Você tem certeza?") do %>
                        <%= image_tag 'https://icons.iconarchive.com/icons/awicons/vista-artistic/16/delete-icon.png' %>
                    <% end %>
                </td>
                <td>
                    <%= link_to "Editar", edit_cidade_path(cidade.id) %>
                </td>
                <td>
                    <%= link_to "Visualizar" ,  cidade%>
                </td>
                <td>
                    <%= link_to(:action => :edit, :id => cidade.id) do %>
                    <%= image_tag 'page_edit.png' %>
                    <% end %>
                </td> 
            </tr>
        <%end%>
    </tbody>
    <%= link_to 'Nova cidade', new_cidade_path %>
</table>

app/views/cidades/new.html.erb
<h1>Criar cidade</h1>

<%= render partial: 'formulario' %>

app/views/cidades/show.html.erb
<p><%= @cidade.nome %></p>

<p><%= @cidade.qtde_habitantes %></p>

app/views/estados/_formulario.html.erb
<% if @estado.errors.any? %>
  <div style='color:red;'>
    Não foi possível salvar a cidade por <%=
    pluralize(@estado.errors.size, 'motivo') %>:
    <ul>
      <% @estado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @estado do |f| %>

  <%= f.label :nome %><br>
  <%= f.text_field :nome, maxlength: 32, required: true %><br>

  <%= f.label :sigla, 'Sigla' %><br>
  <%= f.text_field :sigla,  maxlength: 4, required: true %><br>

  <%= f.submit "Submit" %>
<% end %>

app/views/estados/_lista_de_estados.html.erb
<table>
    <thead>
    <tr><th colspan="2">Lista Estados</th></tr>
    </thead>

    <tr>
        <th>Nome</th>
        <th>Siglas</th>
    </tr>   
    <% estados.each do |estado| %>
    <tr><td><%= estado[:nome] %></td
    ><td><%= estado[:sigla] %> anos</td></tr>    
    <% end %>
</table>

app/views/estados/edit.html.erb
<h1>Editar Estado</h1>

<%= render partial: 'formulario' %>

app/views/estados/index.html.erb
<h1>Lista de Estados</h1>
<table>
    <thead>
        <tr>
            <th>Sigla</th>
            <th>Nome</th>
        <tr>
    <thead>
    <tbody>
        <% @estados.each do |estado|%>
            <tr>
                <td><%= estado.sigla%></td>
                <td><%= estado.nome%></td>
            </tr>
             <td>
                    <%= link_to({:action => :destroy, :id => estado.id},method: :delete,
                        :confirm => "Você tem certeza?") do %>
                        <%= image_tag 'https://icons.iconarchive.com/icons/awicons/vista-artistic/16/delete-icon.png' %>
                    <% end %>
                </td>
                <td>
                    <%= link_to "Editar", edit_estado_path(estado.id) %>
                </td>
                <td>
                    <%= link_to "Visualizar" ,  estado%>
                </td>
                <td>
                    <%= link_to(:action => :edit, :id => estado.id) do %>
                    <%= image_tag 'page_edit.png' %>
                    <% end %>
                </td>
        <%end%>
    </tbody>
    <div style='color:green'>
        <%= flash[:notice] %>
    </div>
    <%= link_to 'Novo Estado', new_estado_path %>
</table>

app/views/estados/new.html.erb
<h1>Criar estado</h1>

<%= render partial: 'formulario' %>

app/views/estados/show.html.erb
<%= @estado.sigla %></p>

<p><%= @estado.nome %></p>

app/views/hello/world.html.erb
<div align='center'>
    <p><h1>Hello World!</h1></p>
    <p> Minha primeria página no rails funcionou! </p>
    <p>Alfabeto: <%= @alfabeto.join(', ')%> </p>
    <p>Hash: <%= @hash.keys.first%>: <%= @hash.values.first%></p>
    <p>Array:</p>
    <% @pessoas.each do |item| %>
        Nome <%= item[:nome] %>Idade; <%= item[:Idade]%><br>
    <% end %>
</div>

app/views/layouts/_cabecalho.html.erb
<div style='color:white; font-size:30px; padding: 10px 10px 5px 0px;
 text-shadow: 1px 1px 4px #A1A1A1;' align='right'>
 Minha aplicação em Ruby on Rails.
</div>

app/views/layouts/_menu.html.erb
<div style='background-color:white; margin:0px 15px 0px 15px;
 padding:4px; border-radius: 4px;-moz-border-radius: 5px;'>

 <%= link_to 'HelloWorld!', '/hello/world' %> |
 <%= link_to 'Criancas', '/pessoas/criancas' %> |
 <%= link_to 'Adultos', '/pessoas/adultos' %> |
 <%= link_to 'Cidades ', '/cidades'%> |
 <%= link_to 'Estados  ', '/estados'%> |
 <%= link_to 'Paises ', '/paises'%>
 <%=  link_to 'Bairros', '/bairros'%>


</div>

app/views/layouts/_rodape.html.erb
<div style='color:gray;' align='center'>
 Desenvolvido por Eduardo, todos os direitos reservados.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helloword</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style='margin:0px; background-color:#600;' >
<table width='100%' height='100%' style='border-spacing: 0;'>
 <tr><td> <%= render :partial => '/layouts/cabecalho' %> </td></tr>
 <tr><td> <%= render :partial => '/layouts/menu' %> </td></tr>
 <tr><td><div style='background-color:white;
 margin:0px 15px 0px 15px; padding:4px;
 border-radius: 4px;-moz-border-radius: 5px;'>
 <%= yield %>
 </div></td></tr>
 <tr><td><%= render :partial => '/layouts/rodape' %></td></tr>
</table>
</html>

app/views/paises/_formulario.html.erb
<% if @pais.errors.any? %>
  <div style='color:red;'>
    Não foi possível salvar o pais por <%=
    pluralize(@pais.errors.size, 'motivo') %>:
    <ul>
      <% @pais.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @pais do |f| %>

  <%= f.label :nome %><br>
  <%= f.text_field :nome, maxlength: 32, required: true %><br>
  
  <%= f.submit "Submit" %>
<% end %>

app/views/paises/_lista_de_paises.html.erb
<table>
    <thead>
    <tr><th colspan="2">Lista Pais</th></tr>
    </thead>

    <tr>
        <th>Nome</th>
    </tr>   
    <% paises.each do |pais| %>
    <tr><td><%= pais[:nome] %></td>
    <% end %>
</table>

app/views/paises/edit.html.erb
<h1>Editar pais</h1>

<%= render partial: 'formulario' %>

app/views/paises/index.html.erb
<h1>Lista de Paises</h1>
<table>
    <thead>
        <tr>
            <th>Nome</th>
        <tr>
    <thead>
    <tbody>
        <% @paises.each do |pais|%>
            <tr>
                <td><%= pais.nome%></td>
               
                <td>
                    <%= link_to({:action => :destroy, :id => pais.id},method: :delete,
                        :confirm => "Você tem certeza?") do %>
                        <%= image_tag 'https://icons.iconarchive.com/icons/awicons/vista-artistic/16/delete-icon.png' %>
                    <% end %>
                </td>
                <td>
                    <%= link_to "Editar", edit_pais_path(pais.id) %>
                </td>
                <td>
                    <%= link_to "Visualizar" ,  pais%>
                </td>
                <td>
                    <%= link_to(:action => :edit, :id => pais.id) do %>
                    <%= image_tag 'page_edit.png' %>
                    <% end %>
                </td> 
            </tr>
        <%end%>
    </tbody>
    <%= link_to 'Nova Pais', new_pais_path %>
</table>

app/views/paises/new.html.erb
<h1>Criar pais</h1>

<%= render partial: 'formulario' %>

app/views/paises/show.html.erb
<p><%= @pais.nome %></p>

app/views/pessoas/_lista_de_pessoas.html.erb

<table>
    <thead>
    <tr><th colspan="2">Tabela pessoas</th></tr>
    </thead>

    <tr>
        <th>Nome</th>
        <th>Idade</th>
    </tr>   
    <% pessoas.each do |pessoa| %>
    <tr><td><%= pessoa[:nome] %></td
    ><td><%= pessoa[:idade] %> anos</td></tr>    
    <% end %>
</table>
 

app/views/pessoas/adultos.html.erb
<p>
    <h1>Lista de Adultos</h1>
</p>

<%= render :partial => 'lista_de_pessoas', :locals => {:pessoas => @adultos} %>

app/views/pessoas/criancas.html.erb
<p>
    <h1>Lista de Crianças </h1>
</p>

<%= render :partial => 'lista_de_pessoas', :locals => {:pessoas => @criancas} %>